# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdminSidebarComponent`.
# Please instead update this file by running `bin/tapioca dsl AdminSidebarComponent`.

class AdminSidebarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
