# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DataBubbleComponent`.
# Please instead update this file by running `bin/tapioca dsl DataBubbleComponent`.

class DataBubbleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
