# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeleteLinkComponent`.
# Please instead update this file by running `bin/tapioca dsl DeleteLinkComponent`.

class DeleteLinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
