# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DescriptionComponent`.
# Please instead update this file by running `bin/tapioca dsl DescriptionComponent`.

class DescriptionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
