# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DescriptionListItemComponent`.
# Please instead update this file by running `bin/tapioca dsl DescriptionListItemComponent`.

class DescriptionListItemComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
