# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FormHeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl FormHeaderComponent`.

class FormHeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
