# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GameKeyComponent`.
# Please instead update this file by running `bin/tapioca dsl GameKeyComponent`.

class GameKeyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
