# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GreenBubbleComponent`.
# Please instead update this file by running `bin/tapioca dsl GreenBubbleComponent`.

class GreenBubbleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
