# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `IncrementComponent`.
# Please instead update this file by running `bin/tapioca dsl IncrementComponent`.

class IncrementComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
