# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InviteLinkMailer`.
# Please instead update this file by running `bin/tapioca dsl InviteLinkMailer`.

class InviteLinkMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def invite_link; end
  end
end
