# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LoginLinkMailer`.
# Please instead update this file by running `bin/tapioca dsl LoginLinkMailer`.

class LoginLinkMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def login_link; end
  end
end
