# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LogoComponent`.
# Please instead update this file by running `bin/tapioca dsl LogoComponent`.

class LogoComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
