# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MagicLinkMailer`.
# Please instead update this file by running `bin/tapioca dsl MagicLinkMailer`.

class MagicLinkMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def send_magic_link; end
  end
end
