# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OrderListComponent`.
# Please instead update this file by running `bin/tapioca dsl OrderListComponent`.

class OrderListComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
