# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OtpComponent`.
# Please instead update this file by running `bin/tapioca dsl OtpComponent`.

class OtpComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
