# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OtpFieldComponent`.
# Please instead update this file by running `bin/tapioca dsl OtpFieldComponent`.

class OtpFieldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
