# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PrimaryButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl PrimaryButtonComponent`.

class PrimaryButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
