# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PrimaryLinkButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl PrimaryLinkButtonComponent`.

class PrimaryLinkButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
