# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecondaryLinkButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl SecondaryLinkButtonComponent`.

class SecondaryLinkButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
