# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecondaryLinkComponent`.
# Please instead update this file by running `bin/tapioca dsl SecondaryLinkComponent`.

class SecondaryLinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
