# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SmallButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl SmallButtonComponent`.

class SmallButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
