# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TableDataBoldComponent`.
# Please instead update this file by running `bin/tapioca dsl TableDataBoldComponent`.

class TableDataBoldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
