# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TableDataComponent`.
# Please instead update this file by running `bin/tapioca dsl TableDataComponent`.

class TableDataComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
