# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TableBodyComponent`.
# Please instead update this file by running `bin/tapioca dsl TableBodyComponent`.

class TableBodyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
