# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TableHeaderFirstColumnComponent`.
# Please instead update this file by running `bin/tapioca dsl TableHeaderFirstColumnComponent`.

class TableHeaderFirstColumnComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
