# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TableHeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl TableHeaderComponent`.

class TableHeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
