# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TinyTableDatumComponent`.
# Please instead update this file by running `bin/tapioca dsl TinyTableDatumComponent`.

class TinyTableDatumComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
