# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TitleComponent`.
# Please instead update this file by running `bin/tapioca dsl TitleComponent`.

class TitleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
