# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ToggleComponent`.
# Please instead update this file by running `bin/tapioca dsl ToggleComponent`.

class ToggleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
