# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `VersionComponent`.
# Please instead update this file by running `bin/tapioca dsl VersionComponent`.

class VersionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
