# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `YellowBubbleComponent`.
# Please instead update this file by running `bin/tapioca dsl YellowBubbleComponent`.

class YellowBubbleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
